In [1]:
import pandas as pd

In [2]:
shop = pd.read_csv("../data/shopping center.csv",sep='\t', engine='python')
suburb = pd.read_csv("../data/suburb_geoinfo.csv")

In [3]:
shop
shop = shop.iloc[:,[0,1,3]]

In [4]:
suburb = suburb.loc[suburb['state'] == "VIC"]
suburb.reset_index()
suburb = suburb.iloc[:,[2,1]]
suburb.columns = ['Suburb', 'postcode']
suburb.drop_duplicates(subset='Suburb',keep='first',inplace=True)
suburb

                       Suburb  postcode
5584                Melbourne      3000
5586           East Melbourne      3002
5587           West Melbourne      3003
5589    St Kilda Road Central      3004
5590       World Trade Centre      3005
...                       ...       ...
16687         Abeckett Street      8006
16688     Collins Street West      8007
16690           Flinders Lane      8009
16691              Law Courts      8010
16692  Little Lonsdale Street      8011

[3164 rows x 2 columns]

In [5]:
shop["Suburb"] = shop.iloc[:,1].str[1:]

In [6]:
df = pd.merge(shop,suburb, how='left',on='Suburb')
df

,Name,Suburb,Location,postcode
0,206 BOURKE STREET Victoria,Melbourne,"GPS: -37.812733,144.966947",3000.0
1,ACLAND COURT SHOPPING CENTRE Victoria,St Kilda,"GPS: -37.868967,144.980617",3182.0
2,ALTONA GATE SHOPPING CENTRE Victoria,Melbourne,"GPS: -37.828989,144.84627",3000.0
3,BALNARRING VILLAGE SHOPPING CENTRE Victoria,Balnarring,"GPS: -38.373199,145.12501",3926.0
4,BARKLY SQUARE Victoria,Brunswick,"GPS: -37.775695,144.962004",3056.0
...,...,...,...,...
186,WODONGA PLAZA Victoria,Wodonga,"GPS: -36.121153,146.881917",3689.0
187,WOODGROVE SHOPPING CENTRE Victoria,Melton,"GPS: -37.686167,144.56127",3337.0
188,WOOLWORTHS WHITEBOX RISE WODONGA Victoria,Wodonga,"GPS: -36.139008,146.892456",3689.0
189,WYNDHAM VALE SQUARE SHOPPING CENTRE Victoria,Wyndham Vale,"GPS: -37.888057,144.607036",3024.0
190,WYNDHAM VILLAGE SHOPPING CENTRE Victoria,Tarneit,"GPS: -37.849333,144.704302",3029.0

In [7]:
# after checking, the null in postcode are caused by no such suburb in suburb_geoinfo.csv
df.isnull().sum()

Name        0
Suburb      0
Location    0
postcode    2
dtype: int64

In [19]:
df= df.dropna()
df['postcode'] = df['postcode'].astype('int')
df

,Name,Suburb,Location,postcode
0,206 BOURKE STREET Victoria,Melbourne,"GPS: -37.812733,144.966947",3000
1,ACLAND COURT SHOPPING CENTRE Victoria,St Kilda,"GPS: -37.868967,144.980617",3182
2,ALTONA GATE SHOPPING CENTRE Victoria,Melbourne,"GPS: -37.828989,144.84627",3000
3,BALNARRING VILLAGE SHOPPING CENTRE Victoria,Balnarring,"GPS: -38.373199,145.12501",3926
4,BARKLY SQUARE Victoria,Brunswick,"GPS: -37.775695,144.962004",3056
...,...,...,...,...
186,WODONGA PLAZA Victoria,Wodonga,"GPS: -36.121153,146.881917",3689
187,WOODGROVE SHOPPING CENTRE Victoria,Melton,"GPS: -37.686167,144.56127",3337
188,WOOLWORTHS WHITEBOX RISE WODONGA Victoria,Wodonga,"GPS: -36.139008,146.892456",3689
189,WYNDHAM VALE SQUARE SHOPPING CENTRE Victoria,Wyndham Vale,"GPS: -37.888057,144.607036",3024
190,WYNDHAM VILLAGE SHOPPING CENTRE Victoria,Tarneit,"GPS: -37.849333,144.704302",3029

In [ ]:
df.to_csv("../data/shopping_with_postcode.csv")